### PR TITLE
Print certificate's SHA512 fingerprint, not its SHA512 hash sum

### PR DESCRIPTION
**Pull request by rjc**

### CODE REVIEW

**Comment by rjc** [comment]
Current instruction has been taken verbatim from [freenode's](https://freenode.net/kb/answer/certfp), with _SHA1_ being replaced by _SHA512_.

Both instructions are wrong as they print certificate's _hash sum_, **not** its fingerprint. The updated command prints the fingerprint as it is being displayed and accepted by _NickServ_, i.e. all lower case and without colons (':'). This makes it for an easy comparison.

Added bonus is that the pipe also works on the OpenBSD, where `sha1sum`, `sha256sum`, and `sha512sum`, equivalent utilities, don't have the suffix _sum_ :^)

**Comment by edk0** [comment]
> Both instructions are wrong as they print certificate's _hash sum_, **not** its fingerprint. The updated command prints the fingerprint as it is being displayed and accepted by _NickServ_, i.e. all lower case and without colons (':'). This makes it for an easy comparison.

The sha512 fingerprint of a certificate _is_ the sha512 hash of its DER encoding, by definition. I have no real opinion on whether the awk way is better, but to my eyes it's a little less forgiving to type.

**Comment by rjc** [comment]
D'oh! Of course it is! _base64_ output fooled me into thinking they're different :^P

However, in it's current for, the command still have several issues, which my PR adresses:

- _base64_ notation is being used, while _NickServ_ uses _hex_
- `-fingerprint` option already exists in _openssl(1)_ so there's no need to use an external tool
- `sha512sum` utulity doesn't exist on _OpenBSD_
- pipe is being reduced from _three_ to _two_ commands ;^)

So, IMHO, this is still an improvement :^D

**Comment by rjc** [comment]
Ping.

**Comment by emersonveenstra** [comment]
@rjc thanks!

**Comment by kurahaupo** [comment]
I had a bit of a dig into the source code and in `openssl/apps/x509.c` I found:
```C
  else if (fingerprint == i)
    {
```
...
```C
    BIO_printf(STDout,"%s Fingerprint=",
                     OBJ_nid2sn(EVP_MD_type(fdig)));
    for (j=0; j<(int)n; j++)
      {
      BIO_printf(STDout,"%02X%c",md[j],
                        (j+1 == (int)n)
                        ?'\n':':');
      }
    }
```
from which it appears that the formatting (with "Blah Fingerprint=", colons, and upper-case hex digits) is not controllable.

But we can still do better in terms of the number of _programs_ that need to run to get the desired output, assuming your shell is Bash or Ksh or Zsh:
```bash
typeset -l sha  # only if you REALLY need lower-case

IFS== read _ sha < <(
    openssl x509 -in libera.pem -noout -fingerprint -sha512
) &&
printf '%s\n' "${sha//:}"
```

**Pull request merged**
