### PR TITLE
Erc: built-in SASL support in emacs 29

### PR DESCRIPTION
**Pull request by dongdigua**
probably need some changes (links?) when it finally releases

### CODE REVIEW

**Comment by mplscorwin** [comment]
Could be simplified further?

From the maintainer of ERC (JP "Neverwas", #erc):

> While I appreciate the effort, I'd rather the patch just replace all existing language in that article with something minimal, like:
>       "[ERC](https://www.gnu.org/software/emacs/erc.html) [supports SASL](http://elpa.gnu.org/packages/doc/erc.html#SASL) and is [available on GNU ELPA](https://elpa.gnu.org/packages/erc.html)."

**Comment by mplscorwin** [comment]
BTW, it is released: ERC 5.5 including initial SQL support dropped earlier this week.

**Comment by mplscorwin** [comment]
I created PR#294 as an alternative.  That would remove the separate page documenting ERC entirely in favor of linking directly to ERC documentation SASL:  https://elpa.gnu.org/packages/doc/erc.html#SASL

**Comment by mplscorwin** [comment]
The above-referenced PR was applied, see: #294 https://github.com/Libera-Chat/libera-chat.github.io/pull/294 

If there are no concerns, this can also be closed.

**Comment by sario528** [comment]
Fixed in #294, closing

**Comment by dongdigua** [comment]
great!

**Pull request closed without merging**
