### PR TITLE
Complete Irssi CertFP instructions and unify network name

### PR DESCRIPTION
**Pull request by ailin-nemui**
The CertFP instructions were incomplete (missing instruction about configuring external). You can also compare the instructions with https://github.com/shabble/irssi-docs/wiki/freenode_certfp

I propose to change the (Irssi-internal) network name to "LiberaChat", it was "libera" and "liberachat"

### CODE REVIEW

**Comment by fluix-dev** [comment]
> I propose to change the (Irssi-internal) network name to "LiberaChat", it was "libera" and "liberachat"

Given that some of the other instructions use `liberachat`, I think keeping it is better for consistency. If it must be changed, it should be changed everywhere.

**Comment by ailin-nemui** [comment]
can you make a list of the other instructions? Irssi networks in its default config are camelised, so ideally that style would be good for Libera Chat. And the proposed addition of Libera Chat to the default Irssi config will also use this spelling, thus it would reduce confusion to have it also like this in the official network side guide

**Comment by fluix-dev** [comment]
A `grep -r "libera"` in `/content/_guides/` reveals it in the following (filtered for the context we're talking about):
```
sasl/weechat.md
sasl/revolution.md
sasl/kvirc.md
sasl/irssi.md
certfp.md
```

**Comment by ailin-nemui** [comment]
Each client might follow their own rules for internal network names, for example there is this open request for weechat: https://github.com/Libera-Chat/libera-chat.github.io/pull/57

**Comment by fluix-dev** [comment]
Yes, but I think all clients should be able to use `liberachat` (or `LiberaChat` should that be preferable) as a network name consistently.

**Comment by emersonveenstra** [comment]
@ailin-nemui Can you please resolve the conflicts? then we can merge it

**Pull request merged**
