### PR TITLE
Irssi sasl: remove version numbers

### PR DESCRIPTION
**Pull request by ailin-nemui**

### CODE REVIEW

**Comment by A-UNDERSCORE-D** [comment]
Is there a particular reason to date these docs to these versions?

**Comment by ailin-nemui** [comment]
The current version of the docs reads very confusing with that one single version explicitly mentioned, that's why I'm suggesting this explicit list as a compromise. The current version was created in #117

**Comment by A-UNDERSCORE-D** [comment]
Its explicitly called out to *not* use anything below 1.2.1 due to a cve. `## Irssi 0.8.18 through 1.2.0`

**Comment by ailin-nemui** [comment]
see, you are also being confused by the current version. the cve it wants to draw attention to is fixed in all of Irssi 1.0.8 or later 1.0, 1.1.3 or later 1.1, and 1.2.1 or later...

**Comment by A-UNDERSCORE-D** [comment]
Ah. So it was backported. In which case I'd suggest a note rather than blindly adding versions to the header.

**Comment by ailin-nemui** [comment]
I guess you could say it like that, although all those versions were released at the same time. There is already a note hidden in the current text but I don't feel like it helps... how would you suggest to improve this situation? The current header is quite misleading at least

**Comment by A-UNDERSCORE-D** [comment]
Drop the version from the header, note in the first paragraph that users will want to use one of the versions, preferably the absolute latest.

**Comment by ailin-nemui** [comment]
I made another attempt taking into account your suggestion

**Pull request merged**
