### PR TITLE
Updating Capitol Hosting Solutions Logos

### PR DESCRIPTION
**Pull request by WaffleThief123**
Updating the Logo for the sponsor page with correctly colored logos for both dark/light mode

as well as an add to the gitignore because mac OS is noisy.

### CODE REVIEW

**Comment by WaffleThief123** [comment]
that... wasn't intended. lemme try that again.

**Comment by WaffleThief123** [comment]
ok, reverted the head repo deletion and pushed changes to our branch/fork. Should be ok to merge in now.

**Comment by spb** [comment]
The PR is still closed and unmergeable - I think you'll need to open a new PR from the recreated branch.

**Comment by WaffleThief123** [comment]
Looks like it's failing a lint due to liberapay returning a 403..

```
Run bundle exec htmlproofer --url-swap "https\://libera.chat:" --assume-extension ./_site
NOTE: nokogumbo: Using Nokogiri::HTML5 provided by Nokogiri. See https://github.com/sparklemotion/nokogiri/issues/2205 for more information.
Running ["LinkCheck", "ImageCheck", "ScriptCheck"] on ["./_site"] on *.html... 


Checking 9[6](https://github.com/Libera-Chat/libera-chat.github.io/actions/runs/3373980905/jobs/5599118152#step:7:7) external links...
Ran on [8](https://github.com/Libera-Chat/libera-chat.github.io/actions/runs/3373980905/jobs/5599118152#step:7:9)0 files!
- ./_site/contributing/donate/index.html
Error:   *  External link https://liberapay.com/liberachat/donate failed: 403 No error



HTML-Proofer found 1 failure!
Error: Process completed with exit code 1.
```

**Pull request merged**
